open_data:
  pedestrian-counting-system-sensor-locations: 
    table_name : sensor_locations
    load_type : upsert
    primary_key : location_id

  pedestrian-counting-system-monthly-counts-per-hour :
    table_name : monthly_counts_per_hour
    load_type : append
    primary_key :